### ISSUE TITLE
[Question]: How to avoid synchronization of the complete VS-Code workspace and instead specify which subdirectory of the VS-Code workspace should be synchronized

### ISSUE THREAD

**Issue by julianbauer12463252** [databricks/databricks-vscode#1097]
**Describe the bug**
If I synchronize my VS-Code-workspace, all files of this workspace get uploaded to Databricks workspace.
This is not possible, in our Kubernetes/Docker-based setup of VS-Code, as the workspace contains vulnerable information which should not be uploaded by the Databricks extension.
How can I specify the path of the local directory within the VS-Code workspace which should be uploaded to Databricks?

**Comment by kartikgupta-db** [comment]
Hi @julianbauer12463252. We ignore everything mentioned in you .gitignore. So you can use that to prevent uploading what you do not want.

**Comment by flamron** [comment]
I have the same bug, I tried to sync VSC (on WSL with Ubuntu) with Databricks and it started to upload all files from my home directory to Databricks Workspace, like: 
.aws
.aws-sam
.cache
...

**Comment by kartikgupta-db** [comment]
@flamron for you case, did you have a specific sub folder open in vscode, and even then the extension started uploading your home folder?
