### ISSUE TITLE
Using the current version of Databricks CLI in the VS Code Extension (0.214.1 instead of 0.212.3)

### ISSUE THREAD

**Issue by kampfhamster83** [databricks/databricks-vscode#1124]
Is it possible, that the newest version of Databricks CLI could be integrated into the extension.
There were some findings, that have been fixed. (e.g. [https://github.com/databricks/cli/issues/1231](https://github.com/databricks/cli/issues/1231))

When we now use VS Code with the extension to develop, the databricks cli in the terminal (inside of VS Code), mostly an old version (v0.212.3) is used and not the new one (v0.214.1), whicht has been provided.

The problem is, that there were some really important bug fixes for us in this version history, and working inside VS Code is currently a bit cumbersome.

Extension Version: 1.2.7 (win32-x64)
CLI Version: v.0.212.3
(checked inside the .vcode-extension-folder)

**Comment by kartikgupta-db** [comment]
@kampfhamster83. Thanks for the reporting the issue. We will be merging a fix soon and releasing it early next week.

**Comment by kampfhamster83** [comment]
Thank you very much for the quick help!

**Comment by kartikgupta-db** [comment]
Hi @kampfhamster83. We just released v1.3.0 with the latest cli (v0.215.0).
