### ISSUE TITLE
[BUG] Magic functions no longer being executed in Interactive Window.

### ISSUE THREAD

**Issue by cyaris** [databricks/databricks-vscode#1191]
**Describe the bug**
Magic functions are no longer being executed in the VS Code Interactive Window.
Running a cell using `# MAGIC %md` will be treated as a Python comment. The same is true for `# MAGIC %run`.

**To Reproduce**
1. Create a Databricks notebook source Python file.
2. Run a command in the notebook using a `MAGIC` function.
3. See that the `MAGIC` function commands are not run, and instead are rendered as comments.

**Screenshots**
<img width="531" alt="Screenshot 2024-04-16 at 5 02 19 PM" src="https://github.com/databricks/databricks-vscode/assets/35279417/cae1d6b5-46b1-4f49-9127-02257a40a920">
<img width="636" alt="Screenshot 2024-04-16 at 5 10 44 PM" src="https://github.com/databricks/databricks-vscode/assets/35279417/60467801-687b-4fb8-b0fd-9dcb015aeab4">

**System information:**
- `macOS Version 14.4.1 (23E224)`
- `Databricks CLI v0.216.0`
- `Python 3.11.0`
- `VS Code 1.88.1`
- `Jupyter v2024.3.1` (Jupyter Extension)
- `Databricks v1.3.0` (Databricks Extension)
- Databricks Cluster
  - `Databricks Connect Enabled`
  - `Databricks Runtime 13.3x`

**Additional context**
The issue began a month or so ago.
I tried changing versions for the Jupyter and Databricks extensions but that didn't help.

**Comment by kartikgupta-db** [comment]
Hi @cyaris. Thanks for reporting this issue. It might be that there is some issue actually running our init script that sets up parsing for this magic. 
* Can you try running command "Databricks: Verify Databricks notebook init scripts". 
* Are you also using synapse extension by any chance? It is known to conflict with our notebooks init script.

**Comment by cyaris** [comment]
Hi @kartikgupta-db, I am not using synapse. How should the command be run?

If I run it as a string I see this...
<img width="489" alt="Screenshot 2024-04-17 at 1 51 25 PM" src="https://github.com/databricks/databricks-vscode/assets/35279417/ecec7379-c0e2-4647-920e-abe82a75223e">

If I run it not as a string I see this...
<img width="482" alt="Screenshot 2024-04-17 at 1 51 28 PM" src="https://github.com/databricks/databricks-vscode/assets/35279417/0e86c706-5632-40e1-a79b-c803c6ba2cb1">

**Comment by kartikgupta-db** [comment]
I meant, running a vscode command. 
On mac
* cmd + shift + p > "Databricks: Verify Databricks notebook init scripts" > enter

**Comment by cyaris** [comment]
@kartikgupta-db getting the following error now in init scripts...

`create_and_register_databricks_globals - ImportError: cannot import name 'AnalyzeArgument' from 'pyspark.sql.udtf'`

**Comment by cyaris** [comment]
@kartikgupta-db I have seen this one too...

`debug_error_string = "UNKNOWN - Error received from peer  {grpc_message: "Missing required field \'UserContext\' in the request.", grpc_status:3, created_time:"2024-04-29T14:57:44.156418-05:00"}"`

**Comment by kartikgupta-db** [comment]
Hi @cyaris. Apologies for the late response. Is this still an issue with the latest version of vscode?

**Comment by a-tanman** [comment]
Note sure if this is helpful - I only managed to get the magic functions and line-by-line execution to work after realising that  the init script expects the `ipynb` notebook to be in the sample directory as `.databricks/` which contains `.databricks.env`.

**Comment by ilia-db** [comment]
@a-tanman thanks for the pointer, that part of the code is indeed problematic, created a fix here: https://github.com/databricks/databricks-vscode/pull/1266

**Comment by ilia-db** [comment]
Published new release (1.3.1) with the fix. @cyaris can you update the extension, make sure databricks connect is enabled, and try running notebooks again?
