### ISSUE TITLE
[BUG] Error in attaching sync destination

### ISSUE THREAD

**Issue by surajongithub1986** [databricks/databricks-vscode#1223]
In the "configure Synch Destination" gear when I select an existing folder or create new it give me the follwoing error

"Error in attaching sync destination : "

1. Go to the Databricks extension 
2. Click on gear next to "Synch Destination - none attached"
3. The command palette will drop with options 
4. select an existing folder in the repo or create new under Users 

![image](https://github.com/databricks/databricks-vscode/assets/56974044/d16a40d5-163a-4725-936d-5f6772d7c5de)

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).

Version: 1.89.0 (user setup)
Commit: b58957e67ee1e712cebf466b995adf4c5307b2bd
Date: 2024-05-01T02:09:22.859Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.19045

3. Databricks Extension Version : 1.3.0 

**Additional context**
I can see the directories getting create ".ide" but still gives the error and the "Uplaod and Run file on databricks" fails with 
Error running command databricks.run.runEditorContents: Local file URI scheme must be file. Found vscode-vfs 
I am guessing this is because of the synch destination issue.

**Comment by ilia-db** [comment]
Hey, can you share additional logs with us? You can find them in the "Databricks" output channel in the VSCode, or check log files directly by executing `Databricks: Open full logs` command.

Also, this error message `Local file URI scheme must be file. Found vscode-vfs` tells me that you might be using [Virtual Workspaces](https://code.visualstudio.com/api/extension-guides/virtual-workspaces)? Our extension work work with virtual workspaces correctly, as we expect to have direct access to the files

**Comment by ilia-db** [comment]
Closing the issue as it's quite old and there was no new responses. Related to this: keep in mind that we've released v2 extension where sync destination is based on Databricks Asset Bundles configuration
