### ISSUE TITLE
[BUG] Can't reset variable overrides

### ISSUE THREAD

**Issue by ilia-db** [databricks/databricks-vscode#1272]
**Describe the bug**
As soon as you edit a `bundlevars` json, both the current value and the default value are set to the override, with the `reset` action doing nothing.

**To Reproduce**
- Create an example python dabs project
- Add this var to the config:
```
variables:
  test:
    description: Test
    default: hello
```
- In the variables explorer click on the cog wheel
- Change the value from `hello` to `123`
- Observe that the Default value also changed  to `123`
<img width="590" alt="Screenshot 2024-07-03 at 13 55 51" src="https://github.com/databricks/databricks-vscode/assets/148094031/d518d89f-73f3-4e8a-a159-916e334beabc">

- Click on `reset` icon and observe that nothing has actually been reseted.

**System information:**

1. MacOS
2. Databricks Extension Version: v2.2.2

**Additional context**
Seems like the override ends up in the `preValidateConfig`, which we don't reset when we delete the bundlevars json

**Comment by kartikgupta-db** [comment]
Also, need to make sure we support non string primary type variables (bool and int).
