### ISSUE TITLE
[BUG] Unable to run R files as workflows via extension

### ISSUE THREAD

**Issue by crankswagon** [databricks/databricks-vscode#1275]
**Describe the bug**
When attempting to run .R files as workflows, extensions errors with 

```
Only Python files can be run as a workflow
```

**To Reproduce**
Install extension
Connect to databricks via OAuth
Click `Run File as Workflow on Databricks` as per [docs](https://docs.databricks.com/en/dev-tools/vscode-ext/index.html)

**Screenshots**
<img width="1156" alt="Screenshot 2024-07-04 at 12 10 03 PM" src="https://github.com/databricks/databricks-vscode/assets/48189996/2946852b-78a6-4e3f-879c-42c015299ed9">

**System information:**

1.
```
Version: 1.89.1 (Universal)
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:24.611Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0
```
2. Databricks Extension Version 
- databricks extension version 1.3.1
- databricks connect version 14.0.2
- cluster DBR 14.3 LTS ML (includes Apache Spark 3.5.0, Scala 2.12)
**Databricks Extension Logs**
Please attach the [databricks extension logs] -> this link is broken

**Additional context**
Python files work correctly as expected.
Tested with prelease version of extension as well, same error

**Comment by ilia-db** [comment]
Hey, we don't support running R files as a workflow, but we can run R notebooks. Does running the code as an R notebooks works for you?
