### ISSUE TITLE
[BUG] After running some notebooks cells gives an error "TypeError: Cannot read properties of undefined (reading 'status')"

### ISSUE THREAD

**Issue by ktakanopy** [databricks/databricks-vscode#1276]
**Describe the bug**
After running some notebooks cells gives an error "TypeError: Cannot read properties of undefined (reading 'status')"

**To Reproduce**
1. Download Databricks extension and databricks power tools
2. Connect to a cluster
3. Create a notebook.ipynb 
4. Run some cells in the notebook connected to a cluster.
5. You will receive an error "TypeError: Cannot read properties of undefined (reading 'status')"

**Screenshots**
![Screenshot 2024-07-05 at 10 48 41](https://github.com/databricks/databricks-vscode/assets/10998362/086cb32a-5e91-40ac-8ac6-18e89b488e63)

**System information:**

1. MacOs Sonoma 14.5
2. Databricks Extension Version: 1.3.1

**Databricks Extension Logs**
- Which log file do I need to send? 

**Additional context**

**Comment by ilia-db** [comment]
Hey, can you provide extension logs? In VSCode you can open command palette and execute "Databricks: Open Full Logs" action. We will open a folder with a couple of files. It would be really helpful if you can paste some of their contents here (unless there's sensitive info of course).

Also, can you try disabling "databricks power tools" extension, restarting the notebook's kernel, and run some cells again? Just to make sure that we understand which extension might be causing it

**Comment by kartikgupta-db** [comment]
@ktakanopy the Databricks Power Tools extension manages notebooks on it's own and provides some custom kernel support. In this case, it overrides our changes to the kernel. So, it would be better if you raise this issue on the https://github.com/paiqo/Databricks-VSCode repo, so that the maintainers of the power tools extension can help out.

**Comment by ktakanopy** [comment]
Ok @kartikgupta-db I created there. Closing.
