### ISSUE TITLE
[FEATURE] able to handle monorepo

### ISSUE THREAD

**Issue by javigoncompte** [databricks/databricks-vscode#1348]
For now the behavior is it opens a new window in that folder where the bundle exists.
The problem is on a monorepo our bundles are inside a projects folder so we want to be able to see all bundles if possible in a mono repo or just not open a new window that is in the projects folder

**Comment by kartikgupta-db** [comment]
We actually support this use case already. You can add the subfolder you want to use the bundle from, as a vscode workspace. https://code.visualstudio.com/docs/editor/workspaces#_untitled-multiroot-workspaces. 

You can also open multiple subdirectories as workspaces as well. We will then show you a selector to pick a specific workspace as the active bundle. You should see a new "Active workspace" line in the Databricks extension's Configuration view.
