### ISSUE TITLE
[BUG] Virtual environment required but not clearly communicated

### ISSUE THREAD

**Issue by dustinvannoy-db** [databricks/databricks-vscode#1357]
**Describe the bug**
Virtual environment is required for extension to be fully usable. Not opposed to forcing use of virtual environment but it isn't clear that is the issue. It feels like it just isn't finding the interpreter that has been selected rather than acknowledging that it is not compatible with using the extension.

**To Reproduce**
1. Open folder without databricks.yml or virtual environment
2. Click on 'Migrate current folder to a Databricks Project'
3. Configure profile.
4. Set interpreter from Command Pallet to a system installed interpreter (Cmd + Shift + P) -> Python: Select Interpreter -> 
5. Open python file to confirm interpreter in bottom right info.
6. Try to install databricks-connect from extensions doesn't provide any feedback.
7. Click on "Python Environment -> Activate an environment ..." only gives environment type option of Venv or Conda
8. "Run File as workflow" still works.
9. "Run current file with Databricks Connect" opens up the selection for environment type.
10. Also, the extension doesn't recognize the interpreter so it looks like nothing is configured.

**Screenshots**
![image](https://github.com/user-attachments/assets/29d6aefd-becc-4d32-85fb-f4204de1051d)
![image](https://github.com/user-attachments/assets/dba4858e-9788-424e-9bcd-45eb440268f1)
![image](https://github.com/user-attachments/assets/fd103469-5769-41d9-85db-7d03d8745129)

**System information:**

Paste the output ot the Help: About command (CMD-Shift-P).
Version: 1.93.0 (Universal)
Commit: 4849ca9bdf9666755eb463db297b69e5385090e3
Date: 2024-09-04T13:02:38.431Z (1 wk ago)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 23.6.0

Databricks Extension Version
2.4.2

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

**Additional context**

**Comment by ilia-db** [comment]
In the 2.4.7 we've reworked the "Python Environment" panel a little. Virtual environment is still required for the databricks connect, but now we don't enforce python versions to match DBR requirements (but will show a warning if they don't match). 

We still use the same quick-pick UI from the python extension for the environment selection. So "Activate an environment ..." action leads to "Select Interpreter" UI, which might be confusing indeed. I'll leave this issue open for now.
