### ISSUE TITLE
[BUG] Interactive debug using databricks-connect not working after update

### ISSUE THREAD

**Issue by casperdamen123** [databricks/databricks-vscode#1359]
**Describe the bug**
After updating the extension, the interactive debugging is not working any more for me

**To Reproduce**
1. Go to 'Run on Databricks'
2. Click on 'Debug current file with Databricks Connect'
3. Select the virtual environment
4. Nothing seems to happen

**Additional context**
Previously, I used the debug pane from VScode directly and this worked well. Now the Databricks extension is also not picking up my virtual environment after selecting it.

![image](https://github.com/user-attachments/assets/66d66a70-ca9f-44fe-b3cb-01f7aa1cbf64)

**Comment by ilia-db** [comment]
Hi, based on the screenshot it seems like your environment has incorrect python version for your selected cluster. The Databricks Connect requires that your local python matches the one used by your cluster. For example for clusters with DBR 14.3, [the requirement is to have python 3.10](https://docs.databricks.com/en/release-notes/runtime/14.3lts.html#system-environment).

In the previous version of the extension we were not enforcing it, but there was too many bugs if the versions were not matching. 

Is is possible for your project to change python version of the environment? Then click on `Activate and environment with Python 3.10` and re-create it, choosing the 3.10.

Or does your environment already has python 3.10 and we still don't recognise it? In that case can you provide more information about your environment? (many what env-manager you used to create it)
