### ISSUE TITLE
[BUG] Databricks Project Init throw error creating Python projects forcing to have Unity Catalog.

### ISSUE THREAD

**Issue by DataSlugger** [databricks/databricks-vscode#1403]
**Describe the bug**
Version 2.4.6 requests Unity Catalog to create the Databricks Python Project; the previous extension, version 2.4.5, never asked for Unity Catalog to create the projects. 

**To Reproduce**
1. Go to 'Databrick Extension'
2. Click on 'Create A New Databricks Project'
3. Pick a Databricks Profile in Configure Databricks Workspace
4. Select Authentication Mode - I use the Default profile with Personal Access Token.
5. Open the folder selection dialog to select the folder location for the new Project.
6. In the Databricks Project Init screen, I use the default Python template.
7. I set a project name
8. I chose No for all sample project stub notebooks.
9. After hitting enter in the last step, the Databrick Project Init throws the error, creating the project looking for Unity Catalog. 

**Screenshots**
![image](https://github.com/user-attachments/assets/27421357-f651-4ec6-a306-231b5ee69704)

![image](https://github.com/user-attachments/assets/e9c0ea0d-ce82-493e-9ffd-99794396c318)

![image](https://github.com/user-attachments/assets/20171f7a-4e55-4765-9de4-e65d1f75de1e)

![image](https://github.com/user-attachments/assets/d103b040-ed41-4142-8919-c824c485e1a9)

**System information:**

1. Visual Studio Code Version.
Version: 1.94.2
Electron: 30.5.1
Os: Windows 11

2. Databricks Extension Version

Name: Databricks
Id: databricks.databricks
Description: IDE support for Databricks
Version: 2.4.6
Publisher: Databricks
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=databricks.databricks

3. Databricks Cluster Details.
Runtime Version: 14.3 LTS
Spark: 3.5.0
Tier: Standard

**Databricks Extension Logs**
**Error:** failed to compute file content for {{.project_name}}/resources/{{.project_name}}.pipeline.yml.tmpl. template: :6:16: executing "" at <default_catalog>: error calling default_catalog: Unity Catalog is not available for feature tier STANDARD_TIER.
**Additional context**

**Comment by ilia-db** [comment]
Thanks for reporting! The issue should be fixed in 2.4.7

In that release we've updated the databricks CLI to 0.231.0, which includes this fix: https://github.com/databricks/cli/pull/1854
