### ISSUE TITLE
[BUG] Incorrect magics handling

### ISSUE THREAD

**Issue by ilia-db** [databricks/databricks-vscode#1424]
**Describe the bug**
Magics that start with the `# MAGIC` comment aren't handled unless they appear at the start of the cell. There's also an unexpected behaviour when executing the magic at the top of the cell - the cell itself is ignored. 

**To Reproduce**

**Screenshots**

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
2. Databricks Extension Version

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

**Additional context**

**Comment by ilia-db** [comment]
Almost all of the magics we handle are actual cell magics, so it makes sense to only process them if they are at the start of the cell. But we also handle `$run` in the same way, which looks incorrect

**Comment by mroy-seedbox** [comment]
Isn't that how `%run` works?

From the [docs](https://docs.databricks.com/en/notebooks/notebook-workflows.html#use-run-to-import-a-notebook):
> %run must be in a cell by itself, because it runs the entire notebook inline.

**Comment by ilia-db** [comment]
Good point. In `ipython` it's possible to have multiple %run commands, but I forgot about databricks differences. In the extension we run things with the local ipython, but it makes more sense to be in line with databricks logic, otherwise it won't be possible to run the same file remotely. 

Going to close the issue and the PR, thanks a lot for the comment
