### ISSUE TITLE
[BUG] setting `databricks.python.envFile` is unknown

### ISSUE THREAD

**Issue by copdips** [databricks/databricks-vscode#1462]
**Describe the bug**

I'm trying to use local `.env` file with the setting `databricks.python.envFile` as per extension doc described [here](https://learn.microsoft.com/en-us/azure/databricks/dev-tools/vscode-ext/settings#env-vars). But in VSCode there's no such settings, and by manually adding the setting in the file `settings.json`, VSCode warns that the setting is unknown.

**Screenshots**
![image](https://github.com/user-attachments/assets/3e80ae1c-d5ff-46e1-9ada-7c12fe77b5c6)

![image](https://github.com/user-attachments/assets/fb422c3e-ed5f-483d-b913-88bf9b66f1ae)

**System information:**

vscode and databricks extension both are latest

**Comment by ilia-db** [comment]
Hi, our docs are outdated there - we no longer expose the `databricks.python.envFile` setting. But you can set the `python.envFile` to your desired path (we read it too and update our internal env var representation, which we use for "Run with DBConnect" commands or for `type: 'databricks'` launch configs).

Does it cover your use case?

**Comment by copdips** [comment]
Thanks for the prompt reply.
Could you please give a example on how to get the env var in the code ?

for example, under the root of my repo there's a file `.env` with content:

```env
AA=11
```

the `.env` file is specified by the `python.envFile` VSCode setting.

When I run `type: 'databricks'` launch configs, from the debug console, `os.getenv('AA')` returns `None`.

**Comment by ilia-db** [comment]
Sorry for the confusion, `type: "databricks"` executes the file remotely, and we indeed don't read env file in this case. We do pass over env vars from the `env` section of the launch config: 

<img width="574" alt="Screenshot 2024-11-22 at 11 36 10" src="https://github.com/user-attachments/assets/dbf1ecc5-4758-4902-8a26-59f0c3cc05c7">


For local runs (Run/Debug with Databricks Connect commands) we load the vars from `python.envFile`. 
<img width="749" alt="Screenshot 2024-11-22 at 11 38 13" src="https://github.com/user-attachments/assets/9610c159-3954-4149-b553-4d4893b02bfb">

You can also "extend" local python launch configuration by adding "databricks: true" to it, which will ensure we execute the local files with our bootstrap logic and load the env vars (but our internal DATABRICKS_* vars to make sure dbconnect can access remote workspace, plus the things from `python.envFile`)

<img width="681" alt="Screenshot 2024-11-22 at 11 47 28" src="https://github.com/user-attachments/assets/bcbead85-c5ef-47c8-a08d-1c951287725e">
(side note, "python" launch type is now deprecated, but we don't yet support "databricks: true" field on `debugpy` config)

**Comment by copdips** [comment]
Thanks a lot, this is working now !

Regarding the local Python launch, I tested both `"type": "python"` and `"type": "debugpy"`, and they both work, althought there's a warning for each:

![image](https://github.com/user-attachments/assets/dce5d285-78af-4780-8732-0c7651bd5531)

**Comment by ilia-db** [comment]
Should be fixed after we merge and release this: https://github.com/databricks/databricks-vscode/pull/1465
