### ISSUE TITLE
Run/debug command doesn't terminate even though completed on cluster

### ISSUE THREAD

**Issue by robkisk** [databricks/databricks-vscode#227]
Noticed that a command from vscode to `saveAsTable` will never end the execution and continues showing it as running even though the spark job completes. Tested this in both a notebook cell and the same command from vscode as follows which takes ~9min to complete. 

```
df = (
    spark.table(tbl_usage_logs_opt)
    .filter(F.col("date") >= F.date_add(F.current_date(), -7))
    .filter((F.col("metric") == "clusterManagerDuration") & (F.col("tags.opType") == "ClusterCreate"))
)
df.write.saveAsTable("robkisk.cluster_size", mode="overwrite")
```

this is what remains in the UI even after table writing is completed:
![image](https://user-images.githubusercontent.com/113189551/202176759-4bf7e946-6a92-416a-9631-5170a206a422.png)

**Comment by virtualdvid** [comment]
It seems the debugger is not working as a debugger, it is just to run the code.

I had the same problem like @robkisk running one of my notebooks. So, I created a new file with only `print('hello')` put a breakpoint and clicked `Run on Darabricks` in `Run and Debug` tab. It just triggered the code but didn't stop in the breakpoint:

![image](https://user-images.githubusercontent.com/33104726/219468084-48a937f2-8f91-44d4-94e7-c4ea022a5654.png)

It also doesn't work if the notebook was created in databricks workspace. It raises a `FileNotFoundError`:

![image](https://user-images.githubusercontent.com/33104726/219468828-cac6c88e-4b46-4bb2-a2f2-13d6f62b28e9.png)

**Comment by kartikgupta-db** [comment]
Hi @virtualdvid 
> So, I created a new file with only print('hello') put a breakpoint and clicked Run on Darabricks in Run and Debug tab. It just triggered the code but didn't stop in the breakpoint.

Currently we don't support debugging. This is something we are actively working on and we should have a solution with dbconnect v2 sometime soon.

**Comment by kartikgupta-db** [comment]
@robkisk we had a bug which forced a 10 minute timeout for all api operations including running code. We have since fixed it. Can you please verify is you still see the same issue on the latest version of the extension. If you do see it, can you please send us your debug logs for the extension.

**Comment by robkisk** [comment]
@kartikgupta-db. Do not notice this issue any longer.
