### ISSUE TITLE
Local Path is not within workspace Error

### ISSUE THREAD

**Issue by jinlow** [databricks/databricks-vscode#443]
I created a new project, and have synced it with databricks, I can confirm the syncing is working, because I can see my local changes being updated in DataBricks.

However, when I run a python notebook using the "Run file as a workflow on Databricks" command, I get the following error.
Local path is not within Workspace.
![image](https://user-images.githubusercontent.com/38221700/218837599-217e2414-f630-4634-8e85-b34d1c7716a8.png)

**Comment by nqtung** [comment]
I got the same issue. it seems this extension doesn't work with Window!

![image](https://user-images.githubusercontent.com/7363015/218861177-85126d26-fb01-4750-b974-2b5b4c3ac285.png)
