### ISSUE TITLE
Profile names including "." do not work for authentication

### ISSUE THREAD

**Issue by tahaum** [databricks/databricks-vscode#447]
Profile names including `.` do not work when configuring the extension. I'm getting the following error message: 

> Connection using "Profile 'X.Y.Z'" failed with error: "resolve: C:\Users\me\.databrickscfg has no X.Y.Z profile configured. Config: profile=X.Y.Z"."

**Comment by fjakobs** [comment]
This is due to an open bug in the ini parser that we are using https://github.com/npm/ini/issues/60
