### ISSUE TITLE
Synchronizing with a symbolic link to a directory hangs

### ISSUE THREAD

**Issue by rhshadrach-8451** [databricks/databricks-vscode#452]
My repo has certain symbolic links to directories. Upon synchronizing, fast progress is made until it hits the symbolic link and then it reports

> Error: read /path/to/symbolic/link: is a directory 

It then hangs (5+ minutes); the status bar says "Building..." with the circle spinning.

If I remove the offending symbolic links, synchronizing works as expected. As a workaround, I am removing the offending symbolic links when working and restoring them before a commit.

**Comment by fjakobs** [comment]
I have a fix, which should get released tomorrow.
