### ISSUE TITLE
pylance reports reportUnknownMemberType 

### ISSUE THREAD

**Issue by kanterov** [databricks/databricks-vscode#464]
`runtime.pyi` doesn't fully specify type names, which causes pylance to report reportUnknownMemberType error.

Example:

```python
dbutils.widgets.text("date", defaultValue=str(datetime.date.today()))
```

> Type of "text" is partially unknown
>  Type of "text" is "(name: str, defaultValue: str, label: str = None) -> Unknown"Pylance[reportUnknownMemberType](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#reportUnknownMemberType)

```python
        @staticmethod
        def text(name: str, defaultValue: str, label: str = None):
```

should be:

```python
        @staticmethod
        def text(name: str, defaultValue: str, label: str = None) -> None:
```

**Comment by kanterov** [comment]
Also typing for `Optional` should is inconsistent between `getArgument` and `text`:
```
        @staticmethod
        def getArgument(name: str, defaultValue: typing.Optional[str] = None) -> str:
```
vs.
```
        @staticmethod
        def text(name: str, defaultValue: str, label: str = None):
```

**Comment by kartikgupta-db** [comment]
Thanks for the report! I will update these typings.
