### ISSUE TITLE
Run as a Workflow on Databricks is not showing fetched results

### ISSUE THREAD

**Issue by virtualdvid** [databricks/databricks-vscode#470]
Tried to run a notebook using `Run as a Workflow on Databricks` and it gets on hold in `Fetching results` status even though the status in Task Run Details is `Succeeded`.

![Screenshot 2023-02-16 at 3 27 41 PM](https://user-images.githubusercontent.com/33104726/219511374-3384af23-b5c3-4bbf-a103-a0e29f69f8fe.png)

It will be cool if vscode can recognized the `.py` files as a notebooks format connected to the databricks cluster. i guess it is in the road map.

vscode already recognize the file as an interactive file:

![image](https://user-images.githubusercontent.com/33104726/219513371-20ac8b13-043e-42b0-930e-7f39d5578cd7.png)

but only shows the local kernels:

![image](https://user-images.githubusercontent.com/33104726/219513570-50b8fb6c-6bb4-4dc3-882e-a71432290cab.png)

**Comment by kartikgupta-db** [comment]
>Tried to run a notebook using Run as a Workflow on Databricks and it gets on hold in Fetching results status even though the status in Task Run Details is Succeeded.

I have also seen this issue, but seems to be transient for me. The backend posts the status as "SUCCEEDED" even when all the results are not yet loaded. We are working on a fix. 

For now you can click on the "Task Run ID" to see the job run on web ui and see the results there.
