### ISSUE TITLE
Add Proxy Support

### ISSUE THREAD

**Issue by wibbico** [databricks/databricks-vscode#476]
Unfortunately, the sync process is not working and it only throws the following error message.

"Get "https://adb-xxxxx.azuredatabricks.net/api/2.0/preview/scim/v2/Me": dial tcp 40.xx.xx.xx:443: i/o timeout

This indicates that the mandatory proxy is not being used. It is set in the env "HTTPS_PROXY".

**Comment by fjakobs** [comment]
There is a known issue when using the extension behind a corporate proxy. The extension itself will use the system proxy but we are using a command line tool, which does not know about the system settings. It does however respect `HTTP_PROXY` and `HTTPS_PROXY` environment variables.

Calling VS Code like this should work:

`HTTPS_PROXY=..... code`

**Comment by wibbico** [comment]
Iam behind a corporate proxy, using vscode from windows with ssh debian backend. The extention is installed on the remote vs code server. HTTPS_PROXY is set as environment variable for both system (windows and debian). It does work for all other extentions or bash tools

There must be some bug/miissing feature

**Comment by fjakobs** [comment]
I'm trying to reproduce your setup with docker-compose. I have a container that runs an HTTP_PROXY (squid3) and a shell  container where I connect to from VS Code. The shell container only has internet access through the proxy. I'm also setting `HTTP_PROXY` and `HTTPS_PROXY` environment variables in the shell container.

When I connect VS Code to the shell container I'm able to use the Databricks extension including sync and I see the requests in the logs of the proxy server.

I think we need to do a bit more debugging.

**Comment by fjakobs** [comment]
Turned out the lower case `http_proxy` is also a valid proxy environment variable. Will be fixed in the next release.
