### ISSUE TITLE
generic timeout of 10mins for all API operations

### ISSUE THREAD

**Issue by sebrahimi1988** [databricks/databricks-vscode#482]
After ~10 minutes of my code running I get the following error in the 'Debug console' on VS Code:

`Error: Timeout: Command [ac708c17-4d65-4dc0-ac72-c8fcc2640dfa] Context [4657927497901906390] Cluster [0209-143310-81qyest8]: Current state of command is Running`

This is an issue when we have long running operations.

**Comment by StevenGeorge3** [comment]
Thank you for raising this. For context I was running a Python script on one of our All-purpose clusters when I encountered this error. 10 minutes is very restrictive for ML pipelines such as model training. Can this limit please be removed completely?

**Comment by fjakobs** [comment]
Thanks for reporting this issue. I agree. 10min timeout for running code on a cluster is indeed not sufficient.
