### ISSUE TITLE
Fail fast when "Files in Repos" is not available.

### ISSUE THREAD

**Issue by fjakobs** [databricks/databricks-vscode#490]
Detect and print an error message when selecting a Workspace that doesn't have Files in Repos enabled. Today the extension only fails during sync after the user has already configured everything.

**Comment by kartikgupta-db** [comment]
At this point of time, we can't detect if Files in Repos is enabled without admin access to workspace. The only way to find this out is to run the sync and have it fail with the correct error message. 

We should have a better solution for files in workspace anyway.
