### ISSUE TITLE
Datasets progress bar stops output from being printed 

### ISSUE THREAD

**Issue by RoelvdBurght** [databricks/databricks-vscode#496]
When using the map function on a dataset object (from the [Huggingface datasets library](https://huggingface.co/docs/datasets/main/en/index)) all output after the map operation is not shown in the debugger console window. See below code and screencap for an example.

``` python
import datasets
import pandas as pd

test_dataset = pd.DataFrame({'test':[1,2,3]})
test_dataset = datasets.Dataset.from_pandas(test_dataset)
print('before map')

test_dataset = test_dataset.map(lambda x: x)

print('after map')
```
![image](https://user-images.githubusercontent.com/25667848/220896424-ec38aed9-8ec0-4b7d-b0fa-2f7e006eeb4b.png)

I believe it due to the progress bar shown by the map function, since deactivating it makes the problem go away.

It has something to do specifically with the datasets library since a regular tqdm progress bar does work:

``` python
import datasets
import pandas as pd
from tqdm import tqdm

test_dataset = pd.DataFrame({'test':[1,2,3]})
test_dataset = datasets.Dataset.from_pandas(test_dataset)
print('before map')

x = 0
for i in tqdm(range(10000)):
    x += 1
print()
print('after map')
```

![image](https://user-images.githubusercontent.com/25667848/220896117-49b770d3-78f8-4b9e-8ca6-6fb30165056a.png)

In addition to the above bug I'd like to check if it is correct that printed output does not get shown when a script fails due to an error. Right now I only get the stack trace following the error and any previous print statements are ignored in the output. I've also checked the logs and tried to write to them but it didn't work. Am I missing something or is this intended?

**Comment by kartikgupta-db** [comment]
Hi @RoelvdBurght. The hugging face library seems to be using tqdm internally as well. Can you check the driver logs in the webui to see if anything is logged there after the map function? I suspect since map uses multiple processes the main process is not getting the correct output stream.

**Comment by kartikgupta-db** [comment]
>In addition to the above bug I'd like to check if it is correct that printed output does not get shown when a script fails due to an error. Right now I only get the stack trace following the error and any previous print statements are ignored in the output. I've also checked the logs and tried to write to them but it didn't work. Am I missing something or is this intended?

Right now we are not able to fetch the print outputs for failed runs when "Run on Databricks" is used. You can run the same script as a workflow with "Run as Workflow on Databricks", where we are able to fetch and display all print outputs for failed runs.

**Comment by RoelvdBurght** [comment]
Hi @kartikgupta-db, I've checked the driver logs for the above test script. There I'm getting both print statements in the standard output but not the map progress bar.
Also, thanks for the tip on running a file as workflow, that will do nicely!
