### ISSUE TITLE
VS Code version compatible issue[BUG]

### ISSUE THREAD

**Issue by asubashteladoc** [databricks/databricks-vscode#523]
**Describe the bug**
Version comaptibility issue with VS CODE version 1.64.2 in Mac OS

**To Reproduce**
Can't install 'databricks.databricks' extension because it is not compatible with the current version of Visual Studio Code (version 1.64.2).

**Screenshots**

![image](https://user-images.githubusercontent.com/98368637/222526384-89403c6c-2a4d-440e-a255-f80f2459a4a0.png)

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
2. Databricks Extension Version

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

**Additional context**

**Comment by kartikgupta-db** [comment]
Hi @asubashteladoc. We currently only support vscode versions >= 1.69.1. Would it be possible to update the extension or are some of your workflows pinned to this version?
