### ISSUE TITLE
Cannot connect to cluster but can connect to workspace

### ISSUE THREAD

**Issue by shuhei-fujita** [databricks/databricks-vscode#525]
**Describe the bug**
Cannot connect to cluster but can connect to workspace

```
$ databricks --version
Version 0.17.4

$ databricks workspace ls
Users

$ databricks clusters list
<clusters ID>  dx-dev-small  RUNNING
```

**Screenshots**

<img width="267" alt="Screenshot 2023-03-03 at 11 04 47" src="https://user-images.githubusercontent.com/38001967/222614187-c443f03f-4b5d-4dcf-aa08-2b56926a3ddb.png">

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).

```
Version: 1.76.0 (Universal)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
```

2. Databricks Extension Version

```
v0.3.2
```

**Comment by shuhei-fujita** [comment]
<img width="699" alt="Screenshot 2023-03-03 at 13 44 48" src="https://user-images.githubusercontent.com/38001967/222633553-44c89d80-e8bf-436b-96f0-31abbeb37527.png">

I've searched clusters and can't find it...🤔

**Comment by shuhei-fujita** [comment]
<img width="729" alt="Screenshot 2023-03-03 at 13 51 20" src="https://user-images.githubusercontent.com/38001967/222634376-014abe52-7849-463c-a2bb-21ab6b7320b8.png">

databricks

**Comment by kartikgupta-db** [comment]
Hi @shuhei-fujita. The extension only created databricks-sample.ide extension. The other one could be a left over from some old, non-ide process.

**Comment by kartikgupta-db** [comment]
>I've searched clusters and can't find it...🤔
It might be the case that your cluster is being filtered out. Can you verify that `databricks.clusters.onlyShowAccessibleClusters`  setting is set to false?

**Comment by shuhei-fujita** [comment]
@kartikgupta-db 
Thank you!!!!

`databricks.clusters.onlyShowAccessibleClusters` was true.
I've searched clusters and can find it.
