### ISSUE TITLE
[BUG] Error loading webview: Error: Could not register service workers: InvalidStateError

### ISSUE THREAD

**Issue by fjakobs** [databricks/databricks-vscode#539]
**Describe the bug**
When opening the webview for "run as Workflow" the following error is shown:

```
Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**To Reproduce**
So far not reproducible

**Note from the Databricks team**: Please leave a message if you are seeing this error. We currently have no way to reproduce and debug it.

**Comment by fjakobs** [comment]
Could be a VS Code issue. See

- https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai
- https://github.com/microsoft/vscode/issues/125993#issuecomment-912439561

**Comment by kartikgupta-db** [comment]
Closing now. No new occurrences of this have been reported. Might be that the latest version of vscode fixed this.
