### ISSUE TITLE
[BUG] Sync works for most files, then hangs, then displays ERROR

### ISSUE THREAD

**Issue by RobindeGrootNL** [databricks/databricks-vscode#551]
I started using the extension a few days ago and I mostly really like it, but the sync functionality seems a bit broken for me. I sync my work to a (new) repo folder in databricks and most files end up there just fine and I can use those files in jobs/workflows, but the sync never completes successfully. It always displays "ERROR" in the state part of the databricks extension. I turned on extra logging and all the upload requests for the files give a 200 response. Running the sync again does update the files in the folder but it again give the "ERROR" response and thus doesn't keep my files automatically synced.

**To Reproduce**
1. Go to the Databricks extension tab.
2. Set up the sync to a new folder in the repos section of Databricks.
3. Click sync.
4. Wait until it uploads (almost) all files but there is no "SUCCESS" state, only "ERROR"

**Screenshots**
![Image 2023-03-13 at 11 33](https://user-images.githubusercontent.com/59803829/224690843-9fcc8f6e-a83f-410d-9100-0d26e208d86b.jpg)

**System information:**
Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:23:45.993Z (1 wk ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin x64 22.2.0
Sandboxed: No

**Additional context**

The files I upload are a mix of .py files that are Databricks notebooks, .ipynb notebooks, and some other (somewhat larger (40MB)) files.

**Comment by kartikgupta-db** [comment]
Hi @RobindeGrootNL , it might be that there is some illegal notebook, which is causing sync to crash at the very end. It might not have enough time to show the proper errors in that case. Would it be possible to share the sync logs. https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks

**Comment by RobindeGrootNL** [comment]
Hi @kartikgupta-db, thanks for your response! That could indeed be the case, I am now reproducing it and waiting for the sync to fail, afterwards I can send you the logs. Is it possible to send them somewhere privately and not here on the issue itself?

**Comment by kartikgupta-db** [comment]
@RobindeGrootNL you can maybe dm me on [linkedin](https://www.linkedin.com/in/kartik-gupta0204/) and I can give you my mail ID then to send the debug logs.

**Comment by EvanJ3** [comment]
I faced similar behaviour when trying to sync files in a repository that had white space. As an example when the file "test script.py" was present in the repo sync would fail with "error test+script.py not in parent directory". After removing the white space the sync passed.

**Comment by RobindeGrootNL** [comment]
@EvanJ3 Thank you for responding! Checking all the filenames and folder names for whitespaces and changing the ones that required changing solved the issue for me as well. So, @kartikgupta-db, in my opinion this issue can be closed unless you want to keep it to implement changes for being more robust to white spaces in filenames.

**Comment by kartikgupta-db** [comment]
We have implemented the fix and it can already be tried out in the latest nightlies.  https://github.com/databricks/databricks-vscode/releases/tag/nightly

**Comment by EvanJ3** [comment]
I can confirm the nightly release linked above fixes the issue
