### ISSUE TITLE
[BUG] Editing a notebook in vscode while syncing removes notebook dashboard, file history and mlflow tracking data

### ISSUE THREAD

**Issue by nemetht** [databricks/databricks-vscode#552]
**Describe the bug**
Editing a notebook in vscode while syncing removes notebook dashboard, file history and mlflow tracking data

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
Version: 1.76.1
Commit: 5e805b79fcb6ba4c2d23712967df89a089da575b
Date: 2023-03-08T16:31:31.010Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-35-generic snap
Sandboxed: Yes
3. Databricks Extension Version v0.3.4

**Comment by kartikgupta-db** [comment]
Hi @nemetht. The sync is a one way sync, so it unfortunately overwrites everything in the remote directory. This includes any existing notebooks with data. We try to be extremely careful about not overwriting critical files by only allowing syncing to repos with .ide extension. We will be moving away from repos to avoid this confusion entirely.
