### ISSUE TITLE
Please also allow Azure Powershell to authenticate (instead of just Azure CLI)

### ISSUE THREAD

**Issue by MrNickArcher** [databricks/databricks-vscode#574]
**Describe the bug**

I cannot install `az` cli to try this extension.
But I can install powershell azure modules; These provide `(Get-AzAccessToken -Resource 2ff814a6-3304-4ab8-85cb-cd0e6f879c1d).token` which should be just as good?

If I could figure out what I need to paste in `.databrickscfg` I could probably make this method work myself. But without a working example I am a bit stuck.

Also, I can't find a way to use a PAT, will that be an option in the future?

Many thanks, hope to use this extension soon :)

**Comment by MrNickArcher** [comment]
> Hi @MrNickArcher . You can already use a pat. You need to add a section to your .databrickscfg. Something like this:
> ...

Thanks @kartikgupta-db that is super helpful :) I will try again. Looking forward to those future integrations. I guess I'll close the issue.

**Comment by fjakobs** [comment]
@MrNickArcher There is a long term fix, where we support logging in with Azure without the CLI but that will take a bit to complete.
