### ISSUE TITLE
[BUG] PATH delimiter bug `:` and `;`, running a powershell-terminal in vscode 

### ISSUE THREAD

**Issue by erikrok** [databricks/databricks-vscode#576]
**Describe the bug**
PATH delimiter bug, running a powershell-terminal in vscode. 
After installing the extension, the PATH delimiter immediately after the path for the databricks extension is `:`, but the rest of the delimiters are `;`.

**Screenshots**
```sh
c:\Users\username\.vscode\extensions\databricks.databricks-0.3.4-win32-x64\bin:C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;
```

**System information:**
Windows 10
VSCode
Powershell terminal
Databricks extension v0.3.4

```

**Comment by erikrok** [comment]
Might be worth checking whether this context is aware of the OS path delimiter?

https://github.com/databricks/databricks-vscode/blob/a944ed027efd433e875255c66c1d7e035891c216/packages/databricks-vscode/src/extension.ts#L67-L72


The notification when installing the extension is using a `:` 
![image](https://user-images.githubusercontent.com/88889633/225907966-015987b7-edf8-4f52-aac2-d8cbe23d4d18.png)

**Comment by kartikgupta-db** [comment]
Hi @erikrok . Thanks for looking into the issue as well! This might be the cause. I will take a look at it.

**Comment by fjakobs** [comment]
Good catch! 
This looks similar to https://github.com/golang/vscode-go/issues/378
Their fix looks rather involved though https://github.com/hyangah/vscode-go/commit/1b637ac6dea53c888f46f83b7684c910269af320
