### ISSUE TITLE
[BUG] Sync destination does not list existing repos

### ISSUE THREAD

**Issue by manikTharaka** [databricks/databricks-vscode#579]
**Describe the bug**
When configuring the extension, the sync destination configuration does not list any repos that are already existing in the Databricks workspace

**To Reproduce**
1. Create remote git repository in Azure Devops
2. Add the repository to the Databricks repos
3. Install the databricks-vscode and setup authentication as per [documentation](https://docs.databricks.com/dev-tools/vscode-ext.html#set-up-authentication)
4. select or create a cluster 
5. Click the configure icon in the Sync Destination 

**System information:**
1. Version: 1.76.0
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:25:16.105Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.4.0-60-generic
Sandboxed: No

2. Databricks Extension Version v0.3.4

**Comment by kartikgupta-db** [comment]
Hi @manikTharaka. We only list repos that have a .ide at the end of their name. This is because the sync is a 1 way sync which can override critical data in already existing repos. The easiest way to setup the extension correctly is to create the repo from the extension itself.
