### ISSUE TITLE
unable to see any notebooks in your Azure Databricks workspace

### ISSUE THREAD

**Issue by imravipaul** [databricks/databricks-vscode#580]
Type: <b>Feature Request</b>

I am unable to see any notebboks in my Azure Databricks Wrokspae after connecting my account with visual studio code. i can see the cluster but on my workspace name. i am uanble to see any existing notebook . 
where i can navigate my notebooks in visual studio code azure databricks extension. 

Extension version: 0.3.4
VS Code version: Code 1.76.2 (ee2b180d582a7f601fa6ecfdad8d9fd269ab1884, 2023-03-14T17:55:54.936Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by fjakobs** [comment]
The extension is designed to work on your code locally and only pushes the code to the workspace for running. The extension does not pull down code and notebooks from the workspace. If you want to work on a notebook you have to export if from the we b interface and then add the notebook file to your local project.
