### ISSUE TITLE
QUESTION: How do I generate complete OpenAPI specs

### ISSUE THREAD

**Issue by jeffreyaven** [databricks/databricks-vscode#584]
I've tried the scripts in `packages/databricks-sdk-js`, namely `openapi:fetch` and `openapi:generate`, this file : `all-internal.json` is required but not included in the source and I cant locate this anywhere else in the Databricks org.  

I can see many (but __NOT__ all specs) are downloadable from the docs site, I am looking to get __ALL__ of the OpenAPI specs for the Databricks control plane API for __ALL__ services, we are not using an SDK.  

Thanks in advance!

**Comment by jeffreyaven** [comment]
HI @mgyucht, our project [__stackql__](https://github.com/stackql/stackql) is basically an SDK itself with a SQL DSL, we have an OpenAPI interface ([`go-openapistackql`](https://github.com/stackql/go-openapistackql)) which builds routes to operations from a providers open API spec (see [`stackql-provider-registry`](https://github.com/stackql/stackql-provider-registry))

**Comment by kartikgupta-db** [comment]
It doesn't seem we are seeing much activity on this issue yet. Closing it for now.
