### ISSUE TITLE
Lower the priority of vscode bin path

### ISSUE THREAD

**Issue by shreyas-goenka** [databricks/databricks-vscode#600]
`/Users/shreyas.goenka/.vscode/extensions/databricks.databricks-0.3.6/bin` has a higher priority in my $PATH than `/opt/homebrew/bin` or `/usr/bin:/bin:/usr/sbin`. This is not ideal since in the future, users might have a separate installment of the bricks cli they want to invoke from the command line. 

`/opt/homebrew/bin:/Users/shreyas.goenka/.vscode/extensions/databricks.databricks-0.3.6/bin` should be lower down the priority when injected into the $PATH

**Comment by mgyucht** [comment]
This is fixed.
