### ISSUE TITLE
[BUG] VSCode doesn't respect `insecure` setting in `.databrickscfg` profile

### ISSUE THREAD

**Issue by fjakobs** [databricks/databricks-vscode#610]
**Describe the bug**
Users might be behind a proxy server, which breaks validation of SSL certificates. The databricks CLI allows turning off certificate validation through the `insecure` settings in the `.databrickscfg` config file. 

The VSCode extension should respect this config setting and in addition also provide a way to configure cert validation as a VSCode setting.

**Comment by mgyucht** [comment]
Not currently planned. This is really an issue for the CLI, so we can open one there if there is a need.
