### ISSUE TITLE
I am experiencing slow responses from my Databricks VS Code library. The VS Code is installed on a PC located in the Japan region, while the Databricks AWS instances are located in the US-East region. Could the slow response times be related to the geographical distance between the two regions?

### ISSUE THREAD

**Issue by samindaroshan** [databricks/databricks-vscode#637]
**Describe the bug**

**To Reproduce**

**Screenshots**

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
2. Databricks Extension Version

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

**Additional context**

**Comment by kartikgupta-db** [comment]
Hi @samindaroshan. Are you experiencing slowness for some particular operations? Is it the UI that is sluggish or something else? Would be great if you can provide some more context on what sort of operations you were running when you experienced slow responses.

The geographical distance should NOT cause noticeable performance drop.
