### ISSUE TITLE
[BUG] Extension does not recognize custom databricks domains

### ISSUE THREAD

**Issue by s4m0r4m4** [databricks/databricks-vscode#664]
**Describe the bug**
I cannot configure the extension for a databricks URL hosted on my company's domain.

**To Reproduce**
1. Open up VS Code, install Databricks extension
2. In the databricks extension window, click "Configure Databricks"
3. Enter the URL for your company-internal databricks, example:  databricks-test.my-company.com
4. See error: `Not a databricks host`

**Screenshots**

![image](https://user-images.githubusercontent.com/8257287/232879524-47ee3b7a-1085-406f-88b5-3a7cde405f46.png)

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
```
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19045
```

3. Databricks Extension Version (`v0.3.8`)

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

**Additional context**

**Comment by kartikgupta-db** [comment]
Hi @s4m0r4m4. Thanks for reporting this bug. We overlooked this. We will try to patch this by the next version.

**Comment by s4m0r4m4** [comment]
Here's the culprit: https://github.com/databricks/databricks-vscode/blob/main/packages/databricks-vscode/src/utils/urlUtils.ts#L25-L27

I would propose that we simply remove that validation check - in my opinion the plugin should not make any assumptions/requirements about the hostname that databricks is running on.

**Comment by s4m0r4m4** [comment]
If we're in agreement I can yank it out.

**Comment by s4m0r4m4** [comment]
@kartikgupta-db - checking in to see if you're onboard with my proposed approach above ^. If so I can open a PR

**Comment by s4m0r4m4** [comment]
@kartikgupta-db

**Comment by kartikgupta-db** [comment]
@s4m0r4m4 We still need this piece of code, but we are adding a fallback if it is not one of the known domains.

**Comment by ausp** [comment]
@kartikgupta-db Was this fixed in the latest release? I'm still seeing the issue.

**Comment by mgyucht** [comment]
@s4m0r4m4 @ausp Are you trying to use the extension with a Private Cloud workspace?

**Comment by s4m0r4m4** [comment]
Sure. I really feel that the validation is overkill for the extension- it feels like if I enter a wrong URL at setup the extension can just throw a connection error and that would be pretty clear.

**Comment by mgyucht** [comment]
The reason I ask is that the extension explicitly does not support Private Cloud workspaces, as they lack key features that the extension depends on. It's not purely a question of whether the connection will succeed or not, it's a question of the set of environments supported by the extension, that we run tests for, and that we provide support for.

**Comment by s4m0r4m4** [comment]
Thanks for the reply! I don't know if I'm using the Private Cloud Workspaces, but we are hosting our own databricks instance (it's not at databricks.com).

What features don't currently work with private cloud Workspaces? I might be willing to help develop the extension to not break in those circumstances. I really liked the following extension, and it worked fine with our databricks instance before the upgrade to use this extension - https://github.com/paiqo/Databricks-VSCode, so I could potentially help get that working again.

**Comment by ajsiripuram-npss** [comment]
@kartikgupta-db is this issue resolved yet? I am running into the same issues as well.  Please help clarify if there's a workaround for the issue. Thank you

**Comment by ausp** [comment]
> I really liked the following extension, and it worked fine with our databricks instance before the upgrade to use this extension - https://github.com/paiqo/Databricks-VSCode

Agreed - my team is now using this for access, and it works well. No complaints. I'll keep an eye out in future in case the Databricks team want to implement the functionality in future.

> The reason I ask is that the extension explicitly does not support Private Cloud workspaces

Ah. It should probably be made slightly more explicit in the VSCode extensions page/READMEs that "Private Cloud" instances are not supported; I can't currently find it mentioned, at least not with those words. Happy to be corrected.

**Comment by kartikgupta-db** [comment]
@ajsiripuram-npss I have a PR out for removing any enforcements on our part for the host. You might run into issues with certain features (such as sync) when running on private cloud, but this atleast let's you use other features such as autocomplete, dbconnect etc.
