### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by limnicholased** [databricks/databricks-vscode#688]
Adding workspace to my VSCode configuration yields a login error.
Some other configurations (using other databricks accounts) work on my system, however my own token and workspace combinations yield a login error.

**Screenshots**
![image](https://user-images.githubusercontent.com/76949707/236111596-8e0199ea-60ca-4606-8949-13e14933e37f.png)

**System information:**

**VSCode** 
Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes

**Comment by raks-gd** [comment]
the same config works for databricks power tools and other extensions. failing for this extension

**Comment by drewbeno123** [comment]
Same problem for me !

**Comment by kartikgupta-db** [comment]
Duplicate #691
