### ISSUE TITLE
[BUG] Extension forcefully strips "https://" from `DATABRICKS_HOST` variable

### ISSUE THREAD

**Issue by anton164** [databricks/databricks-vscode#702]
**Describe the bug**
It seems that the extension manages a local `.databricks/.databricks.env` file which is populated by the connection & cluster configuration.

Despite having the following in `./databrickscfg`:
```
[DEFAULT]
host = https://*.cloud.databricks.com
...
```

The extension loads the following into `.databricks/.databricks.env`:
```
DATABRICKS_HOST="*.cloud.databricks.com"
```

Note that the `https://` is stripped. This breaks other integrations (i.e. MLFlow or dbx) which requires the host value to start with http / httpsw.

**Comment by kartikgupta-db** [comment]
Fixed in the latest release (0.3.15)
