### ISSUE TITLE
[BUG] Unable to sync

### ISSUE THREAD

**Issue by drorata** [databricks/databricks-vscode#720]
**Describe the bug**
I'm unable to run a notebook from a local clone on a running Databricks cluster.

**To Reproduce**
1. Start a cluster from Databricks' web
1. Go to the configuration of Databricks in VScode
2. Connect to the started cluster
3. Create a new sync destination
4. Open a `.py` and try to `Run file as Workflow on Databricks`.
5. Get an error after a few long seconds.

**Screenshots**
<img width="543" alt="image" src="https://github.com/databricks/databricks-vscode/assets/2905978/359b2126-917d-4526-a04f-f151b393ac59">

**System information:**

**Help About**

```
Version: 1.78.2 (Universal)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z (1 wk ago)
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No
```

**Databricks Extension Version:** v0.3.13

**Databricks Extension Logs**
```
[VSCODE] bricks cli path: /Users/dataria/.vscode/extensions/databricks.databricks-0.3.13-darwin-arm64/bin/bricks
[VSCODE] sync command args: sync,.,/Users/dxxxxx@xxxxxxxx.net/.ide/36xxxxxxxxxx,--watch,--output,json,--log-level,debug,--log-file,stderr
--------------------------------------------------------
time=2023-05-19T11:01:39.984+02:00 level=INFO source=root.go:40 msg=start version=0.0.31 args="/Users/daxxxx/.vscode/extensions/databricks.databricks-0.3.13-darwin-arm64/bin/bricks, sync, ., /Users/daxxxx@xxxx.net/.ide/36xxxxxxxxx, --watch, --output, json, --log-level, debug, --log-file, stderr"
time=2023-05-19T11:01:39.987+02:00 level=INFO source=auth_default.go:49 msg="Ignoring pat auth, because metadata-service is preferred" sdk=true
time=2023-05-19T11:01:39.987+02:00 level=INFO source=auth_default.go:49 msg="Ignoring basic auth, because metadata-service is preferred" sdk=true
time=2023-05-19T11:01:39.987+02:00 level=INFO source=auth_default.go:49 msg="Ignoring oauth-m2m auth, because metadata-service is preferred" sdk=true
time=2023-05-19T11:01:39.987+02:00 level=INFO source=auth_default.go:49 msg="Ignoring bricks-cli auth, because metadata-service is preferred" sdk=true
time=2023-05-19T11:01:39.991+02:00 level=DEBUG source=auth_metadata_service.go:98 msg="Refreshed access token from local metadata service, which expires on 2023-05-19T11:01:54+02:00" sdk=true
```

**Additional context**
FWIW, the file I open is in a clone of a repo that's also cloned in the Databricks' workspace.

**Comment by drorata** [comment]
It looks like this:

<img width="1256" alt="image" src="https://github.com/databricks/databricks-vscode/assets/2905978/2f6ef1bc-f0e4-4f17-bd9f-00180b6ab20c">

for a long time and then at some point I see:

<img width="403" alt="image" src="https://github.com/databricks/databricks-vscode/assets/2905978/b3d4ac95-45b7-42ed-8a06-5808b9710265">

in the Output pan on the right

**Comment by markderry** [comment]
I also have this issue, the sync was working and then something happened that broke it. I can make new folders or sync locations however when I initiate a sync of the files it fails with the error above.

**Comment by drorata** [comment]
FWIW, seems like there was an update of the extension (or at least I was asked to restart it) and now it works.
