### ISSUE TITLE
[BUG] `%pip` and `%sh pip` can't be used to install local libraries when running a job from files in workspace.

### ISSUE THREAD

**Issue by kartikgupta-db** [databricks/databricks-vscode#734]
**Describe the bug**
> it ends up running in an ephemeral path which means relative paths don't seem to work properly. this is impacting both %pip install as well as %sh pip install. when doing this via Repos mode, SINGLE_USER cluster would work fine for both. USER_ISOLATION clusters however would have the issue with %pip install but not %sh pip install

**Comment by pahwaranger** [comment]
related slack thread with more details/context: https://databricks.slack.com/archives/C01KSAWFXG8/p1684649197876029?thread_ts=1684177630.804559&cid=C01KSAWFXG8
