### ISSUE TITLE
[BUG] Unable to sync to existing workspace

### ISSUE THREAD

**Issue by SRGAnalytics-MD** [databricks/databricks-vscode#744]
**Describe the bug**
I'm able to sync to a new workspace, however often after the cluster is shutdown and restarted, I am unable to sync again to that same workspace.  As a workaround, I configure a new sync destination.  This gets tedious after a couple of times ...

**To Reproduce**
1. Go to 'Sync Destination'
2. Click on 'Start Synchronisation'
3. See error in screenshot

**Screenshots**
![image](https://github.com/databricks/databricks-vscode/assets/71739828/cbbe992e-2b91-44de-807d-5cc4c0a1316d)

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
Version: 1.78.2 (user setup)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:39:26.248Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

2. Databricks Extension Version
0.3.14

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)
> The logs seem to have a lot of information in them, & it seems it will be visible publicly .. 

**Additional context**

**Comment by JK87iab** [comment]
Actually it happens because I tried to sync a .zip file. After removing it from sync it works

**Comment by kartikgupta-db** [comment]
@SRGAnalytics-MD the logs will be really helpful in this case. Can you ping me on [linkedin](https://www.linkedin.com/in/kartik-gupta0204/) and I can share my email for you to send logs there?

**Comment by SRGAnalytics-MD** [comment]
Apologies @kartikgupta-db , I didn't receive notification of your replay.
In one instance I noted the hint on the error to delete .databrics\sync-snapshots and this has overcome any issues.  I do have another issue now in that I can't sync at all due to a "context deadline exceeded" error, but will raise another ticket.
