### ISSUE TITLE
[BUG] Databricks CLI is not in the $PATH environment variable on the latest Extension

### ISSUE THREAD

**Issue by saadansari-db** [databricks/databricks-vscode#746]
**Describe the bug**
Installing the latest extension does not make the "databricks" cli available because of incorrectly configured path variable.

**To Reproduce**
1. Install the Extension: v0.3.14
2. go to terminal and type "bricks" it will run, now type "databricks" it will not run
3. Run Databricks sync from the extension and see that it finds a path to the correct binary
4. Echo $Path and you will see the path from 4 is not correcty copied over.

**Screenshots**
Sync output
```
[VSCODE] databricks cli path: /Users/saad.ansari/.vscode/extensions/databricks.databricks-0.3.14-darwin-arm64/bin/databricks
[VSCODE] sync command args: sync,.,/Repos/saad.ansari@databricks.com/ide-best-practices.ide,--watch,--output,json
--------------------------------------------------------
Starting synchronization (0 files)
Completed synchronization
```

Echo output
``` 
[VSCODE] databricks cli path: /Users/saad.ansari/.vscode/extensions/databricks.databricks-0.3.14-darwin-arm64/bin/databricks
[VSCODE] sync command args: sync,.,/Repos/saad.ansari@databricks.com/ide-best-practices.ide,--watch,--output,json
--------------------------------------------------------
Starting synchronization (0 files)
Completed synchronization
```
**System information:**
```
Version: 1.78.2 (Universal)
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:44:45.204Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
Sandboxed: Yes
```
**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

**Additional context**

**Comment by kartikgupta-db** [comment]
With recent changes in v1.1.2 this should be fixed as well.
