### ISSUE TITLE
[BUG] `Run File as Workflow on Databricks` Notebook output is not displayed in the output pane

### ISSUE THREAD

**Issue by ravirahul-db** [databricks/databricks-vscode#815]
**Describe the bug**
When Databricks notebook(.py) is executed via `Run File as Workflow on Databricks`, the notebook output is not displayed in the output pane. `Refresh Results` does not help as well. But can see the result on the job's page.

**To Reproduce**
1. Open Databricks Notebook(.py)
2. Use `Run File as Workflow on Databricks` to execute the notebook
3. Output is displayed in the jobs UI but not in the VS Code's output pane

```
# Databricks notebook source
print("111")

# COMMAND ----------

print("222")

# COMMAND ----------

print("333")
```

**Screenshots**
<img width="951" alt="image" src="https://github.com/databricks/databricks-vscode/assets/86963944/240f3f3a-4515-4116-ade6-cf91955e9924">

Expected output to be visible within VS Code as shown in https://github.com/databricks/databricks-vscode/pull/520

https://user-images.githubusercontent.com/88345179/222450373-98e74cd1-1e36-4c8d-a5da-24609d9c44c3.mov

**System information:**
Databricks Extension Version: v1.1.0
```
Version: 1.80.1 (Universal)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:23.298Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
```

**Databricks Extension Logs**
When I perform `Refresh Results` I could see the job result is being fetched but it is not displayed.

```
{"level":"debug","logger":"SDK","loggingFunction":"JobsService.exportRun","message":"https://adb-xxxxx.azuredatabricks.net/api/2.1/jobs/runs/export?run_id=13489","operationId":"712edeb7-753a-4e7e-aa19-0ae630ec7de4","operationName":"JobsService.exportRun","request":{"method":"GET"},"response":{"views":[{"content":"***REDACTED***","name":"test.databricks.notebook.workflow-wrapper","type":"NOTEBOOK"}]},"timestamp":1689672524337}
```
<img width="507" alt="image" src="https://github.com/databricks/databricks-vscode/assets/86963944/69a2f0a9-e391-48f0-9424-f90158be651d">

**Comment by kartikgupta-db** [comment]
The issue doesn't seem consistent. Could be something as simple as network outage. We will add more logging to capture more debug data around "Run as Workflow" command.
