### ISSUE TITLE
[BUG] Magic command %run not found error

### ISSUE THREAD

**Issue by rajaasokan** [databricks/databricks-vscode#816]
**Describe the bug**
Magic command %run not found error

**To Reproduce**
1. Create a Notebook (Python or Scala)
2. Add one cell with Magic %run command
3. Submit the notebook Run file as Workflow on Databricks

**Screenshots**

![Screenshot 2023-07-20 at 14 44 26](https://github.com/databricks/databricks-vscode/assets/102211552/0a8442c9-56b7-45a2-875d-8015ae6ff899)

**System information:**

Version: 1.80.1 (Universal)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:20:23.298Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.5.0
4. Databricks Extension Version
v1.1.0
**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)

**Additional context**

**Comment by kartikgupta-db** [comment]
Hi @rajaasokan. I tried this against a cluster running DBR 13.2. It seems to be working for me. Could you also provide your cluster version? 

Also, the filepaths passed to %run need to be absolute or relative ("./LINES_schema").

**Comment by rajaasokan** [comment]
@kartikgupta-db yes, my bad. Its working.
Closing the issue. Thanks!
