### ISSUE TITLE
[Bug] SparkSession.builder.getOrCreate() : configuration injection is not working

### ISSUE THREAD

**Issue by fludo** [databricks/databricks-vscode#818]
Using a simple code from Advanced Analytics video, I can no longer get this code to work:
```
from pyspark.sql import *
from pyspark.sql.functions import *


`spark = SparkSession.builder.getOrCreate()`
```

Error:

> 

> RuntimeError                              Traceback (most recent call last)
> Cell In[9], line 1
> ----> 1 spark = SparkSession.builder.getOrCreate()
> 
> File [~/databricks-project/.venv/lib/python3.10/site-packages/pyspark/sql/session.py:518](https://vscode-remote+wsl-002bgm-005fwsl.vscode-resource.vscode-cdn.net/home/favrel/databricks-project/~/databricks-project/.venv/lib/python3.10/site-packages/pyspark/sql/session.py:518), in SparkSession.Builder.getOrCreate(self)
>     512         else:
>     513             raise RuntimeError(
>     514                 "Cannot start a remote Spark session because there "
>     515                 "is a regular Spark session already running."
>     516             )
> --> 518 raise RuntimeError(
>     519     "Only remote Spark sessions using Databricks Connect are supported. " +
>     520     "Could not find connection parameters to start a Spark remote session."
>     521 )
>     523 session = SparkSession._instantiatedSession
>     524 if session is None or session._sc._jsc is None:
> 
> RuntimeError: Only remote Spark sessions using Databricks Connect are supported. Could not find connection parameters to start a Spark remote session.

The extension was working a few weeks ago.

Version:
databricks-connect 13.2 (same error with 13.1)
Latest Databricks VSCode extension (1.1.0)
Running in Ubuntu WSL from Windows.
Cluster running version 13.1.x Runtime (not working with 13.2): ` [REQUIRES_SINGLE_PART_NAMESPACE] spark_catalog requires a single-part namespace, but got `xxx`.`yyy`.`

I have checked the following:
Cluster connected
"Message: You can run code on this cluster"
Databricks connect enabled in the status bar.

**Comment by fludo** [comment]
Thanks, with DatabrickSession it works. 
I thinks with this explanation + solution the ticket can be closed

**Comment by jasperputs** [comment]
@kartikgupta-db is there a reason why this is done? Will it be possible in the future to keep using SparkSession instead of DatabricksSession, as this keeps the files cleaner when we want to run them both in VSCode and Databricks?

**Comment by kartikgupta-db** [comment]
Starting from dbr 13.2 DatabricksSession is available in dbr. So the code should be directly portable. cc @nija-at
