### ISSUE TITLE
[BUG] Extension exports DATABRICKS_HOST variable that dbx does not accept

### ISSUE THREAD

**Issue by NodeJSmith** [databricks/databricks-vscode#836]
**Describe the bug**
The extension exports multiple environment variables when loaded. One of these is `DATABRICKS_HOST`. This is being set without the protocol (e.g. my-org-name.cloud.databricks.com). When attempting to deploy to databricks using dbx, an exception is raised by dbx because the host does not have the protocol.

All of my configuration has the protocol included in the databricks host value, I've included screenshots to show that.

**To Reproduce**
1. Open empty folder in VS Code
2. Configure Databricks extension
3. Open new terminal
4. `echo $DATABRICKS_HOST`

**Screenshots**
![image](https://github.com/databricks/databricks-vscode/assets/8505845/4960e090-9a17-4096-8944-e4483af434c7)
![image](https://github.com/databricks/databricks-vscode/assets/8505845/4770db4d-04a3-426f-a362-3a039810c737)
![image](https://github.com/databricks/databricks-vscode/assets/8505845/afb218f8-7a64-43a2-ad85-a35e3ccc5cab)
![image](https://github.com/databricks/databricks-vscode/assets/8505845/04fafaf3-e21e-4298-a50c-aaeb5962b907)
![image](https://github.com/databricks/databricks-vscode/assets/8505845/1813ec05-eca5-4973-8e7c-75d7617c7e41)

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

2. Databricks Extension Version
v1.1.1

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)
This link is no longer valid - I can attach extension logs if necessary but none relate to this and I do not want to have to scrub them if not necessary. If there is a way to generate logs that are more useful that used to be documented in the link, please let me know what they are.

**Additional context**
This seems to be a new issue. This is happening in WSL Ubuntu 22.04 and in Ubuntu 22.04 on an EC2. Both are using zsh, but this happens in bash as well. It does not seem to happen on Windows using Powershell 7 - the extension doesn't seem to export any environment variables there.

**Comment by NodeJSmith** [comment]
The issue was introduced in version 1.1.0, I have downgraded to 1.0.0 for now.

**Comment by kartikgupta-db** [comment]
Hi @NodeJSmith. I have made a fix PR. We will release it in the next version (>v1.1.1)
