### ISSUE TITLE
[BUG] .* in .gitignore syncs an empty folder

### ISSUE THREAD

**Issue by dilwong** [databricks/databricks-vscode#837]
**Describe the bug**
Perhaps this is intended behavior, but `.*` in `.gitignore` causes "Sync Destination" to sync an empty folder.

**To Reproduce**
1. With the Databrick vscode extension, use "Sync Destination" to synchronize a local folder and Databricks workspace location.
2. Add `.*` to the `.gitignore` file.
3. All files are deleted from the remote Databricks workspace location.

**System information:**

1. Version: 1.81.1 (Universal)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:20:33.924Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
2. Databricks Extension Version v1.1.1

**Comment by dilwong** [comment]
Yes, `.*` is intended to ignore all files and folders starting with a `.`, but it is not intended to mean the current directory (`.`) or parent directory (`..`).

**Comment by pietern** [comment]
@kartikgupta-db We can pull this into the next extension release with a CLI bump.

**Comment by pietern** [comment]
This is fixed in the latest VS Code release (v1.1.2).

@dilwong Can you confirm this now works for you?

**Comment by dilwong** [comment]
The synchronization works fine now.
