### ISSUE TITLE
Detect and append user agent from SPARK_CONNECT_USER_AGENT variable if present

### ISSUE THREAD

**Issue by jthomasmock** [databricks/databricks-vscode#854]
For the extension, it would be great to detect if the `SPARK_CONNECT_USER_AGENT` is already defined and use that variable or append it to the hard-coded user agent.

The current behavior appears to overwrites the User Agent details: https://github.com/databricks/databricks-vscode/blob/3b0cadc74fbb35a323acf23ffd4768437de88e65/packages/databricks-vscode/src/utils/envVarGenerators.ts#L119-L131

**Comment by kartikgupta-db** [comment]
Hi @jthomasmock, is this something that is still needed? I can try pulling this in the next release if required.

**Comment by jthomasmock** [comment]
> Hi @jthomasmock, is this something that is still needed? I can try pulling this in the next release if required.

Yes - it would be greatly appreciated to include this in the next release!

**Comment by kartikgupta-db** [comment]
@jthomasmock can you take a look at the PR https://github.com/databricks/databricks-vscode/pull/870/files and verify it works for you?
