### ISSUE TITLE
[BUG] OAuth U2M does not open a window

### ISSUE THREAD

**Issue by duffwang** [databricks/databricks-vscode#871]
**Describe the bug**

Hi we are experiencing the following issue:

In v1.1.2:

1) Type in host name
2) Select Oauth U2M
3) No browser window pops up, unable to auth

in v1.1.1:
1) Type in host name
2) Select Oauth U2M 
3) Browser window pops up, allowing authentication

**Comment by kartikgupta-db** [comment]
@duffwang, thanks for reporting this issue. This is a bug and we are investigating a fix. Can you downgrade to v1.1.1 to unblock for the time being?

**Comment by kartikgupta-db** [comment]
@duffwang we released an update (v1.1.3) that should address this issue. Can you verify the same?
