### ISSUE TITLE
[BUG] Bash Terminal being overridden by databricks CLI within devcontainer

### ISSUE THREAD

**Issue by asos-davidstafford** [databricks/databricks-vscode#885]
**Describe the bug**
When running running within a dev container using a linux (slim buster) docker image. Once built and opened within VS Code the bash terminal does not understand basic bash commands.  the extension appear to have overridden it.  probably related to this fix

![image](https://github.com/databricks/databricks-vscode/assets/138133648/82aa7e36-1d2e-4f15-b7b6-032ab93024fa)

**To Reproduce**
1. DockerFile setting slim-buster image and installing AzureCLIDeb 
2. Create .devcontainer and include python and databricks extensions
3. Open vscode within the dev container
4. Awaiting it the build and try to run any bash command within the terminal .. eg 'ls'

**Screenshots**

1.1.1 version of Environment Changes (Terminal environment contributions)
![image](https://github.com/databricks/databricks-vscode/assets/138133648/791e4d43-f5a2-4969-8489-1997b8973f3b)

1.1.3 version
![image](https://github.com/databricks/databricks-vscode/assets/138133648/8a3fd715-c951-4279-a2ff-ee2dc5921a4b)

**System information:**

Version: 1.82.2 (system setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

5. 1.1.3  .. Issue appears to have come in 1.1.2

**Databricks Extension Logs**
N/A . doesn't get that far

**Additional context**

path going from 
- `PATH=/root/.vscode-server/extensions/databricks.databricks-1.1.1-linux-x64/bin:${env:PATH}`
to
- `PATH=${env:PATH}/root/.vscode-server/extensions/databricks.databricks-1.1.2-linux-x64/bin:`
appears to be the problem

I believe the fix is putting the : after ${env:PATH}
ie. .. should be PATH=${env:PATH}:/root/.vscode-server/extensions/databricks.databricks-1.1.2-linux-x64/bin

**Comment by kartikgupta-db** [comment]
Aah. Thanks for reporting this issue @asos-davidstafford. Will fix it in the next release (Thursday). Sorry for the inconvenience. Please feel free to downgrade to unblock.
