### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by shannonlowder** [databricks/databricks-vscode#891]
**Describe the bug**
Sync fails at the end of the first sync. Sync does not stay enabled. You must manually hit sync each time you wish to sync. The output only displays:
```
NameError: name 'response' is not defined
>>>
```

**To Reproduce**
1. connect to your workspace with a PAT
2. Click on the sync button in the databricks pane
3. view error in the output screen

**System information:**

1. Paste the output ot the `Help: About` command (CMD-Shift-P).
Windows 11
VSC version 1.82.2

2. Databricks Extension Version
1.1.3

**Databricks Extension Logs**
Please attach the [databricks extension logs](https://docs.databricks.com/dev-tools/vscode-ext.html#send-usage-logs-to-databricks)
bad link, is there an updated link?

**Comment by kartikgupta-db** [comment]
Hi @shannonlowder. We are backed up with a couple of updates, due to some release issues. A couple of sync fixes are coming in the upcoming releases (happening on Monday). Can you test it again then, and let us know if it is still an issue.

**Comment by kartikgupta-db** [comment]
Closing this issue for now. But feel free to reopen it or create a new one if you see this bug persist.
