### ISSUE TITLE
Connection to databricks failed 

### ISSUE THREAD

**Issue by Kartiktrishul** [databricks/databricks-vscode#942]
While configuring databricks connection, I get
Error running command databricks.connection.configureWorkspace: Command failed
Error: cannot parse config file: key-value delimiter not found

**Comment by ilia-db** [comment]
Hey, based on the error, the most probable root cause is that you have corrupted `~/.databrickscfg` file. 

It has to be in a correct `ini` format, something like:
```ini
[PROFILE]
token = secret
host = https://...
```

See more info about configuration file here - https://docs.databricks.com/en/dev-tools/auth.html#config-profiles
