### ISSUE TITLE
Error running command databricks.connection.configureWorkspace: spawn UNKNOWN

### ISSUE THREAD

**Issue by jaavout** [databricks/databricks-vscode#947]
I installed Databricks extension for VS Code. When I click on "Configure Databricks", it shows an error: `Error running command databricks.connection.configureWorkspace: spawn UNKNOWN`. From `sdk-and-extension-logs.json` I found following:

```
{
  "error": {
    "code": "UNKNOWN",
    "errno": -4094,
    "message": "spawn UNKNOWN",
    "stack": "Error: spawn UNKNOWN\n\tat ChildProcess.spawn (node:internal/child_process:413:11)\n\tat spawn (node:child_process:817:9)\n\tat execFile (node:child_process:360:17)\n\tat node:child_process:253:21\n\tat node:electron/js2c/asar_bundle:2:3177\n\tat CliWrapper.getBundleSchema (c:\\Users\\{user}\\.vscode\\extensions\\databricks.databricks-1.2.3-win32-x64\\out\\extension.js:70680:30)\n\tat generateBundleSchema (c:\\Users\\{user}\\.vscode\\extensions\\databricks.databricks-1.2.3-win32-x64\\out\\extension.js:77151:34)\n\tat activate (c:\\Users\\{user}\\.vscode\\extensions\\databricks.databricks-1.2.3-win32-x64\\out\\extension.js:85708:3)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n\tat async v.n (c:\\Users\\{user}\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:124:6205)\n\tat async v.m (c:\\Users\\{user}\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:124:6168)\n\tat async v.l (c:\\Users\\{user}\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\vs\\workbench\\api\\node\\extensionHostProcess.js:124:5625)",
    "syscall": "spawn"
  },
  "level": "error",
  "logger": "Extension",
  "message": "Failed to load bundle schema: ",
  "timestamp": 1700640182385
}

```
I have tried:
- Reinstalling VS Code
- Reinstalling the extension
- Reinstalling portable version of VS Code and installing the extension on it

But no luck, problem stays the same. I'm running Windows 11 x64.

Any tips with this one?

**Comment by ilia-db** [comment]
Haven't been able to reproduce the issue so far. Are you using x64 or arm version of windows?

**Comment by jaavout** [comment]
I'm using x64 Windows. Any tips on how to work around the problem?

**Comment by kartikgupta-db** [comment]
This seems like an issue with generating bundle schema. This should not be a non blocking silent error. @ilia-db we should do a pass over the usages of this function to make sure it is non blocking.

**Comment by ilia-db** [comment]
Not sure it is - the logs are probably unrelated, but I'll double check.
I'm pretty sure the configuration wizard fails with the same error though, we just don't log it and only show in the warning notification. There are reports of similar "spawn UNKNOWN" errors under windows in node, but I can't find any obvious reason why it might be happening. Maybe a path to vscode installation has some weird symbols?

**Comment by ilia-db** [comment]
Hey, we've found a similar report here: https://github.com/databricks/databricks-vscode/issues/616#issuecomment-1597387914

The problem is most probably with the lack of permissions to execute the CLI binary that we bundle with the extension. The extension can't resolve it by itself, but I've updated the error messaging to help diagnose this problem.
